# Generated by Django 4.2.6 on 2023-10-23 01:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clase_Cuenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_clase', models.IntegerField()),
                ('nombre_clase', models.CharField(max_length=30)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'ClaseCuenta',
                'verbose_name_plural': 'ClaseCuentas',
            },
        ),
        migrations.CreateModel(
            name='Grupo_Cuenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_grupo', models.IntegerField()),
                ('nombre_grupo', models.CharField(max_length=30)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'GrupoCuenta',
                'verbose_name_plural': 'GrupoCuentas',
            },
        ),
        migrations.CreateModel(
            name='Cuenta_Cuenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_cuenta', models.IntegerField()),
                ('nombre_cuenta', models.CharField(max_length=50)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
                ('clase_cuenta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistema_contable.clase_cuenta')),
                ('grupo_cuenta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistema_contable.grupo_cuenta')),
            ],
            options={
                'verbose_name': 'CuentaCuenta',
                'verbose_name_plural': 'CuentaCuentas',
            },
        ),
    ]
