# Generated by Django 4.2.6 on 2023-10-24 15:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClaseCuenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Cuenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('clase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistema_contable.clasecuenta')),
            ],
        ),
        migrations.CreateModel(
            name='Transaccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('concepto', models.TextField()),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('iva', models.BooleanField()),
                ('abono_clase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='abonos', to='sistema_contable.clasecuenta')),
                ('abono_cuenta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='abonos', to='sistema_contable.cuenta')),
                ('cargo_clase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cargos', to='sistema_contable.clasecuenta')),
                ('cargo_cuenta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cargos', to='sistema_contable.cuenta')),
            ],
        ),
    ]
