# Generated by Django 4.2.6 on 2023-10-24 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema_contable', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transaccion',
            options={'verbose_name': 'Transacción', 'verbose_name_plural': 'Transacciones'},
        ),
        migrations.AlterField(
            model_name='transaccion',
            name='iva',
            field=models.CharField(choices=[('CreditoFiscal', 'IVA Crédito Fiscal'), ('DebitoFiscal', 'IVA Débito Fiscal'), ('Ninguno', 'Ninguno')], default='Ninguno', max_length=15),
        ),
    ]
