# Generated by Django 4.2.6 on 2023-10-24 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema_contable', '0002_alter_transaccion_options_alter_transaccion_iva'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuenta',
            name='saldo',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
