# Generated by Django 4.2.6 on 2023-10-24 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema_contable', '0003_cuenta_saldo'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuenta',
            name='codigoCA',
            field=models.CharField(default='ValorPredeterminado', max_length=10),
        ),
    ]
