# Generated by Django 4.2.6 on 2023-10-25 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema_contable', '0004_cuenta_codigoca'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transaccion',
            options={},
        ),
        migrations.AlterField(
            model_name='cuenta',
            name='clase',
            field=models.IntegerField(choices=[(1, 'Activo'), (2, 'Pasivo'), (3, 'Capital'), (4, 'Otros')]),
        ),
    ]
