# Generated by Django 4.2.6 on 2023-10-25 17:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sistema_contable', '0005_alter_transaccion_options_alter_cuenta_clase'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transaccion',
            options={'verbose_name': 'Transacción', 'verbose_name_plural': 'Transacciones'},
        ),
        migrations.AlterField(
            model_name='cuenta',
            name='clase',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistema_contable.clasecuenta'),
        ),
    ]
