# Generated by Django 4.2.6 on 2023-10-25 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sistema_contable', '0006_alter_transaccion_options_alter_cuenta_clase'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaccion',
            name='abono_clase',
        ),
        migrations.RemoveField(
            model_name='transaccion',
            name='cargo_clase',
        ),
    ]
