# Generated by Django 4.2.6 on 2023-11-07 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema_contable', '0007_remove_transaccion_abono_clase_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transaccion',
            options={},
        ),
        migrations.AlterField(
            model_name='cuenta',
            name='codigoCA',
            field=models.CharField(max_length=10),
        ),
    ]
